### ISSUE TITLE
Fix build to support Node 18 without losing support for Node 16

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/requestNetwork#1009]
# Problem
`yarn build`  breaks with Node 18

# Details

Node v18 LTS
```
mantisclone@mantisclone-Inspiron-7620:~/projects/requestNetwork$ node -v
v18.12.1
```

Error
```
Error: error:0308010C:digital envelope routines::unsupported
```

# Solution

Quoted from: https://stackoverflow.com/a/73027407
> Use an up-to-date version of Node.js, and also use packages that are up-to-date with security fixes.
>
> For many people, the following command will fix the issue:
>
> ```
> npm audit fix --force
> ```
> However, be aware that, for complex builds, the above command will pull in breaking security fixes that can potentially break your build.

# Full log

<details>
<summary>full build log</summary>
<p>

```
mantisclone@mantisclone-Inspiron-7620:~/projects/requestNetwork$ yarn build
yarn run v1.22.19
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 24 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@requestnetwork/data-format' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/types' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/multi-format' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/utils' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/currency' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/data-access' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/transaction-manager' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/advanced-logic' in 0.3s:
$ tsc -b tsconfig.build.json
lerna info run Ran npm script 'build' in '@requestnetwork/request-logic' in 0.4s:
$ tsc -b tsconfig.build.json
lerna ERR! yarn run build exited 1 in '@requestnetwork/epk-signature'
lerna ERR! yarn run build stdout:
$ run-s build:commonjs build:umd
$ tsc -b tsconfig.build.json
$ webpack
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/ts-loader/dist/index.js:58:5)
    at successLoader (/home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/home/mantisclone/projects/requestNetwork/packages/epk-signature/node_modules/ts-loader/dist/index.js:23:5)
    at LOADER_EXECUTION (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/mantisclone/projects/requestNetwork/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/mantisclone/projects/requestNetwork/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/mantisclone/projects/requestNetwork/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/mantisclone/projects/requestNetwork/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
error Command failed with exit code 1.
ERROR: "build:umd" exited with 1.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@requestnetwork/epk-signature'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</p>
</details>

---

Migrated from Asana: https://app.asana.com/0/1203912381456855/1205300974037126/f

**Comment by MantisClone** [comment]
@OjusWiZard reported that ethers v5 is not compatible with node v20. Migrating to ethers v6 is a major change that we're not ready to tackle right now. Thus, I am reducing the scope and removing the node v20 compatibility from this issue.

**Comment by MantisClone** [comment]
A quick note - to prove compatibility with both node v16 and v18, I think that the test suite should build and run with both node v16 and node v18. Unless there a better way to prove compatibility?
