### ISSUE TITLE
Fix `SyntaxError: Unexpected token`

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/requestNetwork#1101]
# Problem

Error is logged on the Gnosis Chain Gateway occasionally (5 times in the last month). https://cloudlogging.app.goo.gl/epKTVHXdXc3hwfp76

Variants:
```
SyntaxError: Unexpected token u in JSON at position 1
    at JSON.parse (<anonymous>)
    at parse (/node/node_modules/body-parser/lib/types/json.js:89:19)
    at /node/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/node/node_modules/raw-body/index.js:224:16)
    at done (/node/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/node/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

```
SyntaxError: Unexpected token @ in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/node/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/node/node_modules/body-parser/lib/types/json.js:83:15)
    at /node/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/node/node_modules/raw-body/index.js:224:16)
    at done (/node/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/node/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

```
SyntaxError: Unexpected token t in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/node/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/node/node_modules/body-parser/lib/types/json.js:83:15)
    at /node/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/node/node_modules/raw-body/index.js:224:16)
    at done (/node/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/node/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

---

Migrated from Asana: https://app.asana.com/0/1203912381456855/1205300970356585/f

**Comment by MantisClone** [comment]
Closing as Old
