### ISSUE TITLE
Error in interacting with RequestEthereum contract using web3

### ISSUE THREAD

**Issue by atvanguard** [RequestNetwork/requestNetwork#58]
Hey, solidity newbie here and playing with the request network libraries.
I tried writing a script that interacts with the `RequestEthereum` smart contract using web3. I understand that it is better to do so using the js library but I am still curious.

Steps to reproduce:
```
npm run ganache
```

```
npm run testdeploy
> @requestnetwork/request-network.js@0.7.4 testdeploy /Users/arpit/projects/dao-invoices/contract_deps/requestNetwork/packages/requestNetwork.js
> ts-node ./test/deploy

creator: 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
RequestCore - address : 0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0
RequestEthereum - address : 0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da
TestToken - address : 0x345cA3e014Aaf5dcA488057592ee47305D9B3e10
RequestBitcoinNodesValidation - address : 0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF
RequestERC20 - address : 0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F
adminAddTrustedCurrencyContract: 0xf25186B5081Ff5cE73482AD761DB0eB0d25abfBF
adminAddTrustedCurrencyContract: 0x8f0483125FCb9aaAEFA9209D8E9d7b9C8B9Fb90F
adminAddTrustedCurrencyContract: 0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da
setFeesPerTenThousand: 10
maxFees: 120000000000000
```

and then I run this script
```
const requestArtifacts = require('requestnetworkartifacts').default;
const requestEthereumJson = requestArtifacts('private', 'last-RequestEthereum');

var Web3 = require('web3');
var web3 = new Web3("ws://localhost:8545");

async function execute() {
  var RequestEthereum = new web3.eth.Contract(requestEthereumJson.abi, '0xF12b5dd4EAD5F743C6BaA640B0216200e89B60Da', {
    from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57', // default from address
    gasPrice: '20000000000' // default gas price in wei, 20 gwei in this case
  });
  // console.dir(RequestEthereum, {depth: null});
  const tx = await RequestEthereum.methods.createRequestAsPayee(
    ['0x627306090abaB3A6e1400e9345bC60c78a8BEf57'],
    ['0x627306090abaB3A6e1400e9345bC60c78a8BEf57'],
    [1000000000],
    '0xf17f52151ebef6c7334fad080c5704d77216b732',
    '0xf17f52151ebef6c7334fad080c5704d77216b732',
    'randomdata'
  ).send({
    from: '0x627306090abaB3A6e1400e9345bC60c78a8BEf57', // default from address
    gasPrice: '20000000000', // default gas price in wei, 20 gwei in this case
    gas: 89999999
  });
  // console.dir(tx, {depth: null});
  console.log(tx);
}

execute();
```

I get this error:
```
node scripts/requestEthereum.js
(node:69099) UnhandledPromiseRejectionWarning: Error: Returned error: VM Exception while processing transaction: revert
    at Object.ErrorResponse (/Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at /Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/web3-providers-ws/src/index.js:111:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/web3-providers-ws/src/index.js:88:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/arpit/projects/ethereum-scripts/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Users/arpit/projects/ethereum-scripts/node_modules/web3/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

In the ganache console, I get
```
eth_sendTransaction

  Transaction: 0x8c7e80385c2f9bf340d27bbad2ee318b791db5504cc9d4d63dd19e1078ec7294
  Gas usage: 40631
  Block Number: 11
  Block Time: Wed Aug 08 2018 13:32:57 GMT+0530 (IST)
  Runtime Error: revert
```

I tried to debug this for a day but unable to. I would appreciate any help with this, or in general some guidance on how to debug `Error: Returned error: VM Exception while processing transaction: revert` transactions.

Thank you!

**Comment by romaric-juniet** [comment]
Hey! One thing I can see from your code is that you're missing the fees. 
Get the amount of the fees through `collectEstimation` ([doc here](https://docs-smart-contracts.request.network/docs/RequestEthereum/)) and add a `value: feeValue` to the object in parameter of `send`

**Comment by atvanguard** [comment]
Ahh, it worked. Quite silly of me to overlook that. Thank you.

In general what is the correct way to debug `Error: Returned error: VM Exception while processing transaction: revert` transactions? Is it not possible to get an error trace that actually helps?

**Comment by romaric-juniet** [comment]
No problem. If you find other issues using the smart contracts directly, you can get inspiration from our implementation in the js lib.
It's difficult to debug revert transactions. I found the easiest in the case you have is to follow the code and look at each require. The code is relatively small and it usually doesn't take long before finding the source of the problem.
We [recently added reasons](https://github.com/RequestNetwork/requestNetwork/commit/0102cac2c743f390d1112d268dcd9a209070824a#diff-6e30511cb923ae531e5f7f8882dee0cbL55) to the require calls that will help debugging, when the tooling is available
